### ISSUE TITLE
Cannot build desktop:dist

### ISSUE THREAD

**Issue by vga101** [langurmonkey/gaiasky#233]
Hi,
with the most recent commit, I have problems of building and running Gaia Sky via `./gradlew desktop:dist` - see below. Running via `./gradlew desktop:run` works, however. 

```
$ git describe
1.5.0-239-gfe97f02
$ ./gradlew desktop:dist
Configuration on demand is an incubating feature.

> Configure project :

BUILD INFO FROM GIT
===================
git tag: 1.5.0
git rev: fe97f02
buildtime: Tue Dec 19 16:44:47 CET 2017
builder: me
system: Linux host 3.13.0-77-generic x86_64


BUILD VARIABLES AND INFO
========================
base dir: .../gaiasky
tag.rev: 1.5.0.fe97f02
dist name: gaiasky-1.5.0.fe97f02
dist dir: .../gaiasky/releases/gaiasky-1.5.0.fe97f02
packages name: packages-1.5.0.fe97f02
packages dir: .../gaiasky/releases/packages-1.5.0.fe97f02

Creating desktop jar file
Creating core jar file
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to /home/tsagrista/Programs/android/ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

BUILD SUCCESSFUL in 1s
9 actionable tasks: 6 executed, 3 up-to-date

$ releases/gaiasky-1.5.0.fe97f02/gaiasky   
/usr/lib/jvm/java-8-oracle/bin/java  -Xms2g -Xmx3g -XX:+UseConcMarkSweepGC -cp "/lhome/vgaibler/prog/solsys-explorer/gaiasky/releases/gaiasky-1.5.0.fe97f02/lib/*" gaia.cu9.ari.gaiaorbit.desktop.GaiaSkyDesktop 
java.io.FileNotFoundException: data/dummyversion (Datei oder Verzeichnis nicht gefunden)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at gaia.cu9.ari.gaiaorbit.desktop.util.DesktopConfInit.<init>(DesktopConfInit.java:70)
        at gaia.cu9.ari.gaiaorbit.desktop.GaiaSkyDesktop.main(GaiaSkyDesktop.java:112)
java.lang.NullPointerException
        at gaia.cu9.ari.gaiaorbit.desktop.util.DesktopConfInit.initGlobalConf(DesktopConfInit.java:100)
        at gaia.cu9.ari.gaiaorbit.util.ConfInit.initialize(ConfInit.java:13)
        at gaia.cu9.ari.gaiaorbit.desktop.GaiaSkyDesktop.main(GaiaSkyDesktop.java:112)

```

Also, building a Debian package with `./gradlew desktop:createDeb` creates a package that complains on installation about a missing desktop file:
```
# dpkg -i gaiasky-test.deb 
(Reading database ... 59256 files and directories currently installed.)
Preparing to unpack gaiasky-test.deb ...
Unpacking gaiasky (1.5.0.6a61035) over (1.5.0.6a61035) ...
Setting up gaiasky (1.5.0.6a61035) ...
chmod: cannot access ‘/opt/gaiasky/gaiasky.desktop’: No such file or directory
mv: cannot stat ‘/opt/gaiasky/gaiasky.desktop’: No such file or directory
```

Any chance that some files are not being copied to the respective directories or archives?

**Comment by langurmonkey** [comment]
The first error is due to gradle 4.4 doing things in a slightly different way. As a workaround in the meantime, you can just run the ``gradlew desktop:dist`` command twice. That should work, as the version file is created in the first run (but not included in the jar for some obscure reason). In the second run the file is correctly included in the jar. I'll look into this when I have some time (and I'm back to work from holydays ;) ).

About the second error, I do not maintain or use the ``createDeb`` target. I guess I created it to experiment with the base ``dpkg-deb`` command, but it might well be outdated.

**Comment by vga101** [comment]
Thanks for the information - fix on first error works and builds the respective release. Enjoy your holidays, merry Christmas, and please ignore my issues till you're back - just submitting so that I won't forget... ;-)
