### ISSUE TITLE
Crash with TGAS GPU dataset

### ISSUE THREAD

**Issue by vga101** [langurmonkey/gaiasky#236]
Running the current revision fe97f02 (built with ./gradlew desktop:dist), the TGAS GPU dataset (version 1.5.1, http://wwwstaff.ari.uni-heidelberg.de/gaiasandbox/files/20171204_tgas_gpu_gaiasky_1.5.1.tar.gz) crashes the code:

```
$ LC_ALL=C releases/gaiasky-1.5.0.fe97f02/gaiasky
/usr/lib/jvm/java-8-oracle/bin/java  -Xms2g -Xmx3g -XX:+UseConcMarkSweepGC -cp "/home/me/gaiasky-tests/releases/gaiasky-1.5.0.fe97f02/lib/*" gaia.cu9.ari.gaiaorbit.desktop.GaiaSkyDesktop
Display mode set to 1280x720, fullscreen: false
18:17:06: GaiaSky - GLSL version: 4.50 NVIDIA
18:17:07: JsonLoader - 1 objects loaded from file data/particles-tgas.json
18:17:07: JsonLoader - 6 objects loaded from file data/meshes.json
18:17:07: JsonLoader - 9 objects loaded from file data/planets.json
18:17:07: JsonLoader - 16 objects loaded from file data/moons.json
18:17:07: JsonLoader - 4 objects loaded from file data/satellites.json
18:17:07: JsonLoader - 4 objects loaded from file data/asteroids.json
18:17:07: JsonLoader - 9 objects loaded from file data/orbits_planet.json
18:17:07: JsonLoader - 16 objects loaded from file data/orbits_moon.json
18:17:07: JsonLoader - 4 objects loaded from file data/orbits_asteroid.json
18:17:07: JsonLoader - 1 objects loaded from file data/orbits_satellite.json
18:17:07: JsonLoader - 15 objects loaded from file data/extra.json
18:17:07: JsonLoader - 3 objects loaded from file data/locations.json
18:17:07: JsonLoader - 260 objects loaded from file data/locations_earth.json
18:17:07: JsonLoader - 1,923 objects loaded from file data/locations_moon.json
18:17:07: GeoJsonLoader - 180 objects loaded from file data/countries/countries.geo.json
18:17:07: ConstellationsLoader - 88 constellations initialized
18:17:07: ConstelBoundariesLoader - Constellations boundaries initialized with 5,636 points
18:17:07: NBGLoader - Catalog loaded: 868 stars
18:17:07: MWSCLoader - Catalog loaded: 3,016 stars
18:17:07: BinaryDataProvider - Loading data file: data/catalog/tgashyg.bin
18:17:07: Error: StarGroup - com.badlogic.gdx.utils.GdxRuntimeException: File not found: data/catalog/tgashyg.bin (Internal)
18:17:07: Orbit data loaded: data/orbit/orb.MERCURY.dat (82 points)
18:17:07: Orbit data loaded: data/orbit/orb.VENUS.dat (81 points)
18:17:07: Orbit data loaded: data/orbit/orb.EARTH.dat (80 points)
18:17:07: Orbit data loaded: data/orbit/orb.MARS.dat (80 points)
18:17:07: Orbit data loaded: data/orbit/orb.JUPITER.dat (80 points)
18:17:07: Orbit data loaded: data/orbit/orb.SATURN.dat (80 points)
18:17:07: Orbit data loaded: data/orbit/orb.URANUS.dat (80 points)
18:17:07: Orbit data loaded: data/orbit/orb.NEPTUNE.dat (80 points)
18:17:07: Orbit data loaded: data/orbit/orb.PLUTO.dat (80 points)
18:17:07: Orbit data loaded: data/orbit/orb.MOON.dat (82 points)
18:17:07: Orbit data loaded: Phobos orbit (94 points)
18:17:07: Orbit data loaded: Deimos orbit (101 points)
18:17:07: Orbit data loaded: Amalthea orbit (101 points)
18:17:07: Orbit data loaded: Io orbit (101 points)
18:17:07: Orbit data loaded: Europa orbit (101 points)
18:17:07: Orbit data loaded: Ganymede orbit (101 points)
18:17:07: Orbit data loaded: Callisto orbit (101 points)
18:17:07: Orbit data loaded: Prometheus orbit (101 points)
18:17:07: Orbit data loaded: Titan orbit (101 points)
18:17:07: Orbit data loaded: Rhea orbit (101 points)
18:17:07: Orbit data loaded: Dione orbit (101 points)
18:17:07: Orbit data loaded: Tethys orbit (101 points)
18:17:07: Orbit data loaded: Enceladus orbit (101 points)
18:17:07: Orbit data loaded: Mimas orbit (101 points)
18:17:07: Orbit data loaded: Janus orbit (101 points)
18:17:07: Orbit data loaded: Vesta orbit (101 points)
18:17:07: Orbit data loaded: Ceres orbit (101 points)
18:17:07: Orbit data loaded: Pallas orbit (101 points)
18:17:07: Orbit data loaded: Hygieia orbit (101 points)
18:17:07: Orbit data loaded: data/orbit/orb.GAIA.dat (6,248 points)
18:17:07: PointDataProvider - 57,332 objects loaded from file data/galaxy/galaxy_40000particles.dat
18:17:07: PointDataProvider - 80 objects loaded from file data/galaxy/galaxy_80particles.dat
18:17:08: SDSSDataProvider - 327,421 objects loaded from file data/sdss/sdss_dr12.csv
18:17:08: PointDataProvider - 10,000 objects loaded from file data/oort/oort_10000particles.dat
18:17:08: SceneGraph - Inserting 6,425 nodes into the scene graph...
18:17:08: Error: java.lang.NullPointerException
18:17:08: Initializing renderer and GUI
18:17:11: SceneGraphRenderer - Max texture size: 16384^2 pixels
18:17:11: SceneGraphRenderer - Depth buffer size: 24 bits
Exception in thread "LWJGL Application" java.lang.NullPointerException
        at gaia.cu9.ari.gaiaorbit.interfce.SpacecraftGui.buildGui(SpacecraftGui.java:212)
        at gaia.cu9.ari.gaiaorbit.interfce.SpacecraftGui.doneLoading(SpacecraftGui.java:187)
        at gaia.cu9.ari.gaiaorbit.GaiaSky.reinitialiseGUI2(GaiaSky.java:444)
        at gaia.cu9.ari.gaiaorbit.GaiaSky.doneLoading(GaiaSky.java:337)
        at gaia.cu9.ari.gaiaorbit.GaiaSky.render(GaiaSky.java:526)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

```
The required file actually is there despite the message saying that it isn't:
```
$ ls -l android/assets/data/catalog/tgashyg.bin
-rwxrwxr-x 1 me me 104888854 Dez  1 13:57 android/assets/data/catalog/tgashyg.bin
```

This does not happen with the TGAS LOD data 1.5.1.

**Comment by langurmonkey** [comment]
I just tried with the current master (a9a77db4) and it works just fine, so I'm not sure what's going on :-|

**Comment by langurmonkey** [comment]
Make sure that the file is in the right folder (`$GS/releases/gaiasky-xxxxx/data/catalog`) and not only in the base dev folder `$GS/android/assets/data/catalog`. That file is **NOT** copied automatically.

**Comment by vga101** [comment]
That helped, thanks.
`cp -r android/assets/data/catalog releases/gaiasky-xxxxx/data/`
Was just surprised because that step is not needed for TGAS LOD data (these files are copied into the releases directory).
